2020-02-22 20:45:17,713 DEBUG app.py 29 logging.debug.
2020-02-22 20:45:17,714 INFO app.py 30 logging.info.
2020-02-22 20:45:17,714 WARNING app.py 31 logging.warning.
2020-02-22 20:45:17,714 ERROR app.py 32 logging.error.
2020-02-22 20:45:17,714 CRITICAL app.py 33 logging.critical.
2020-02-22 20:45:17,996 DEBUG app.py 29 logging.debug.
2020-02-22 20:45:17,997 INFO app.py 30 logging.info.
2020-02-22 20:45:17,997 WARNING app.py 31 logging.warning.
2020-02-22 20:45:17,997 ERROR app.py 32 logging.error.
2020-02-22 20:45:17,997 CRITICAL app.py 33 logging.critical.
2020-02-25 12:34:59,058 DEBUG app.py 29 logging.debug.
2020-02-25 12:34:59,059 INFO app.py 30 logging.info.
2020-02-25 12:34:59,059 WARNING app.py 31 logging.warning.
2020-02-25 12:34:59,059 ERROR app.py 32 logging.error.
2020-02-25 12:34:59,059 CRITICAL app.py 33 logging.critical.
2020-02-25 12:34:59,336 DEBUG app.py 29 logging.debug.
2020-02-25 12:34:59,336 INFO app.py 30 logging.info.
2020-02-25 12:34:59,336 WARNING app.py 31 logging.warning.
2020-02-25 12:34:59,336 ERROR app.py 32 logging.error.
2020-02-25 12:34:59,336 CRITICAL app.py 33 logging.critical.
2020-02-25 13:39:13,401 DEBUG app.py 29 logging.debug.
2020-02-25 13:39:13,402 INFO app.py 30 logging.info.
2020-02-25 13:39:13,402 WARNING app.py 31 logging.warning.
2020-02-25 13:39:13,402 ERROR app.py 32 logging.error.
2020-02-25 13:39:13,402 CRITICAL app.py 33 logging.critical.
2020-02-25 13:39:13,669 DEBUG app.py 29 logging.debug.
2020-02-25 13:39:13,669 INFO app.py 30 logging.info.
2020-02-25 13:39:13,669 WARNING app.py 31 logging.warning.
2020-02-25 13:39:13,669 ERROR app.py 32 logging.error.
2020-02-25 13:39:13,669 CRITICAL app.py 33 logging.critical.
2020-02-25 13:48:12,346 DEBUG app.py 29 logging.debug.
2020-02-25 13:48:12,346 INFO app.py 30 logging.info.
2020-02-25 13:48:12,347 WARNING app.py 31 logging.warning.
2020-02-25 13:48:12,347 ERROR app.py 32 logging.error.
2020-02-25 13:48:12,347 CRITICAL app.py 33 logging.critical.
2020-02-25 13:48:32,411 DEBUG app.py 29 logging.debug.
2020-02-25 13:48:32,411 INFO app.py 30 logging.info.
2020-02-25 13:48:32,411 WARNING app.py 31 logging.warning.
2020-02-25 13:48:32,411 ERROR app.py 32 logging.error.
2020-02-25 13:48:32,411 CRITICAL app.py 33 logging.critical.
2020-02-25 13:48:43,084 DEBUG app.py 29 logging.debug.
2020-02-25 13:48:43,084 INFO app.py 30 logging.info.
2020-02-25 13:48:43,084 WARNING app.py 31 logging.warning.
2020-02-25 13:48:43,084 ERROR app.py 32 logging.error.
2020-02-25 13:48:43,084 CRITICAL app.py 33 logging.critical.
2020-02-25 13:48:43,351 DEBUG app.py 29 logging.debug.
2020-02-25 13:48:43,351 INFO app.py 30 logging.info.
2020-02-25 13:48:43,351 WARNING app.py 31 logging.warning.
2020-02-25 13:48:43,351 ERROR app.py 32 logging.error.
2020-02-25 13:48:43,351 CRITICAL app.py 33 logging.critical.
2020-02-25 14:12:17,841 DEBUG app.py 29 logging.debug.
2020-02-25 14:12:17,842 INFO app.py 30 logging.info.
2020-02-25 14:12:17,843 WARNING app.py 31 logging.warning.
2020-02-25 14:12:17,843 ERROR app.py 32 logging.error.
2020-02-25 14:12:17,843 CRITICAL app.py 33 logging.critical.
2020-02-25 14:12:38,989 DEBUG app.py 29 logging.debug.
2020-02-25 14:12:38,989 INFO app.py 30 logging.info.
2020-02-25 14:12:38,989 WARNING app.py 31 logging.warning.
2020-02-25 14:12:38,989 ERROR app.py 32 logging.error.
2020-02-25 14:12:38,989 CRITICAL app.py 33 logging.critical.
2020-02-25 14:12:52,318 DEBUG app.py 29 logging.debug.
2020-02-25 14:12:52,318 INFO app.py 30 logging.info.
2020-02-25 14:12:52,318 WARNING app.py 31 logging.warning.
2020-02-25 14:12:52,318 ERROR app.py 32 logging.error.
2020-02-25 14:12:52,318 CRITICAL app.py 33 logging.critical.
2020-02-25 14:13:00,054 DEBUG app.py 29 logging.debug.
2020-02-25 14:13:00,055 INFO app.py 30 logging.info.
2020-02-25 14:13:00,055 WARNING app.py 31 logging.warning.
2020-02-25 14:13:00,055 ERROR app.py 32 logging.error.
2020-02-25 14:13:00,055 CRITICAL app.py 33 logging.critical.
2020-02-25 14:13:14,689 DEBUG app.py 29 logging.debug.
2020-02-25 14:13:14,689 INFO app.py 30 logging.info.
2020-02-25 14:13:14,689 WARNING app.py 31 logging.warning.
2020-02-25 14:13:14,689 ERROR app.py 32 logging.error.
2020-02-25 14:13:14,689 CRITICAL app.py 33 logging.critical.
2020-02-25 14:13:37,274 DEBUG app.py 29 logging.debug.
2020-02-25 14:13:37,274 INFO app.py 30 logging.info.
2020-02-25 14:13:37,274 WARNING app.py 31 logging.warning.
2020-02-25 14:13:37,274 ERROR app.py 32 logging.error.
2020-02-25 14:13:37,274 CRITICAL app.py 33 logging.critical.
2020-02-25 14:14:50,221 DEBUG app.py 29 logging.debug.
2020-02-25 14:14:50,221 INFO app.py 30 logging.info.
2020-02-25 14:14:50,221 WARNING app.py 31 logging.warning.
2020-02-25 14:14:50,221 ERROR app.py 32 logging.error.
2020-02-25 14:14:50,221 CRITICAL app.py 33 logging.critical.
2020-02-25 14:15:24,443 DEBUG app.py 29 logging.debug.
2020-02-25 14:15:24,443 INFO app.py 30 logging.info.
2020-02-25 14:15:24,443 WARNING app.py 31 logging.warning.
2020-02-25 14:15:24,443 ERROR app.py 32 logging.error.
2020-02-25 14:15:24,443 CRITICAL app.py 33 logging.critical.
2020-02-25 14:15:24,689 DEBUG app.py 29 logging.debug.
2020-02-25 14:15:24,690 INFO app.py 30 logging.info.
2020-02-25 14:15:24,690 WARNING app.py 31 logging.warning.
2020-02-25 14:15:24,690 ERROR app.py 32 logging.error.
2020-02-25 14:15:24,690 CRITICAL app.py 33 logging.critical.
2020-02-25 14:20:49,468 DEBUG app.py 29 logging.debug.
2020-02-25 14:20:49,468 INFO app.py 30 logging.info.
2020-02-25 14:20:49,468 WARNING app.py 31 logging.warning.
2020-02-25 14:20:49,468 ERROR app.py 32 logging.error.
2020-02-25 14:20:49,468 CRITICAL app.py 33 logging.critical.
2020-02-25 14:20:49,695 DEBUG app.py 29 logging.debug.
2020-02-25 14:20:49,696 INFO app.py 30 logging.info.
2020-02-25 14:20:49,696 WARNING app.py 31 logging.warning.
2020-02-25 14:20:49,696 ERROR app.py 32 logging.error.
2020-02-25 14:20:49,696 CRITICAL app.py 33 logging.critical.
2020-02-25 14:37:18,414 DEBUG app.py 29 logging.debug.
2020-02-25 14:37:18,414 INFO app.py 30 logging.info.
2020-02-25 14:37:18,414 WARNING app.py 31 logging.warning.
2020-02-25 14:37:18,414 ERROR app.py 32 logging.error.
2020-02-25 14:37:18,414 CRITICAL app.py 33 logging.critical.
2020-02-25 14:37:48,694 DEBUG app.py 29 logging.debug.
2020-02-25 14:37:48,694 INFO app.py 30 logging.info.
2020-02-25 14:37:48,694 WARNING app.py 31 logging.warning.
2020-02-25 14:37:48,694 ERROR app.py 32 logging.error.
2020-02-25 14:37:48,694 CRITICAL app.py 33 logging.critical.
2020-02-25 14:37:48,942 DEBUG app.py 29 logging.debug.
2020-02-25 14:37:48,945 INFO app.py 30 logging.info.
2020-02-25 14:37:48,945 WARNING app.py 31 logging.warning.
2020-02-25 14:37:48,945 ERROR app.py 32 logging.error.
2020-02-25 14:37:48,946 CRITICAL app.py 33 logging.critical.
2020-02-25 14:38:07,288 DEBUG app.py 29 logging.debug.
2020-02-25 14:38:07,289 INFO app.py 30 logging.info.
2020-02-25 14:38:07,289 WARNING app.py 31 logging.warning.
2020-02-25 14:38:07,289 ERROR app.py 32 logging.error.
2020-02-25 14:38:07,289 CRITICAL app.py 33 logging.critical.
2020-02-25 14:40:56,437 DEBUG app.py 29 logging.debug.
2020-02-25 14:40:56,437 INFO app.py 30 logging.info.
2020-02-25 14:40:56,437 WARNING app.py 31 logging.warning.
2020-02-25 14:40:56,437 ERROR app.py 32 logging.error.
2020-02-25 14:40:56,437 CRITICAL app.py 33 logging.critical.
2020-02-25 14:40:56,670 DEBUG app.py 29 logging.debug.
2020-02-25 14:40:56,670 INFO app.py 30 logging.info.
2020-02-25 14:40:56,670 WARNING app.py 31 logging.warning.
2020-02-25 14:40:56,670 ERROR app.py 32 logging.error.
2020-02-25 14:40:56,670 CRITICAL app.py 33 logging.critical.
2020-02-25 14:42:04,178 DEBUG app.py 29 logging.debug.
2020-02-25 14:42:04,178 INFO app.py 30 logging.info.
2020-02-25 14:42:04,179 WARNING app.py 31 logging.warning.
2020-02-25 14:42:04,179 ERROR app.py 32 logging.error.
2020-02-25 14:42:04,179 CRITICAL app.py 33 logging.critical.
2020-02-25 14:42:33,934 DEBUG app.py 29 logging.debug.
2020-02-25 14:42:33,934 INFO app.py 30 logging.info.
2020-02-25 14:42:33,934 WARNING app.py 31 logging.warning.
2020-02-25 14:42:33,934 ERROR app.py 32 logging.error.
2020-02-25 14:42:33,934 CRITICAL app.py 33 logging.critical.
2020-02-25 14:42:36,479 DEBUG app.py 29 logging.debug.
2020-02-25 14:42:36,479 INFO app.py 30 logging.info.
2020-02-25 14:42:36,479 WARNING app.py 31 logging.warning.
2020-02-25 14:42:36,479 ERROR app.py 32 logging.error.
2020-02-25 14:42:36,479 CRITICAL app.py 33 logging.critical.
2020-02-25 14:42:36,817 DEBUG app.py 29 logging.debug.
2020-02-25 14:42:36,817 INFO app.py 30 logging.info.
2020-02-25 14:42:36,817 WARNING app.py 31 logging.warning.
2020-02-25 14:42:36,817 ERROR app.py 32 logging.error.
2020-02-25 14:42:36,817 CRITICAL app.py 33 logging.critical.
2020-02-25 14:46:16,295 DEBUG app.py 29 logging.debug.
2020-02-25 14:46:16,295 INFO app.py 30 logging.info.
2020-02-25 14:46:16,295 WARNING app.py 31 logging.warning.
2020-02-25 14:46:16,295 ERROR app.py 32 logging.error.
2020-02-25 14:46:16,295 CRITICAL app.py 33 logging.critical.
2020-02-25 14:46:16,616 DEBUG app.py 29 logging.debug.
2020-02-25 14:46:16,616 INFO app.py 30 logging.info.
2020-02-25 14:46:16,616 WARNING app.py 31 logging.warning.
2020-02-25 14:46:16,616 ERROR app.py 32 logging.error.
2020-02-25 14:46:16,616 CRITICAL app.py 33 logging.critical.
2020-02-25 14:48:14,667 DEBUG app.py 29 logging.debug.
2020-02-25 14:48:14,668 INFO app.py 30 logging.info.
2020-02-25 14:48:14,668 WARNING app.py 31 logging.warning.
2020-02-25 14:48:14,668 ERROR app.py 32 logging.error.
2020-02-25 14:48:14,668 CRITICAL app.py 33 logging.critical.
2020-02-25 14:48:15,011 DEBUG app.py 29 logging.debug.
2020-02-25 14:48:15,011 INFO app.py 30 logging.info.
2020-02-25 14:48:15,011 WARNING app.py 31 logging.warning.
2020-02-25 14:48:15,011 ERROR app.py 32 logging.error.
2020-02-25 14:48:15,011 CRITICAL app.py 33 logging.critical.
2020-02-25 14:50:33,859 DEBUG app.py 29 logging.debug.
2020-02-25 14:50:33,860 INFO app.py 30 logging.info.
2020-02-25 14:50:33,860 WARNING app.py 31 logging.warning.
2020-02-25 14:50:33,860 ERROR app.py 32 logging.error.
2020-02-25 14:50:33,860 CRITICAL app.py 33 logging.critical.
2020-02-25 14:50:34,306 DEBUG app.py 29 logging.debug.
2020-02-25 14:50:34,306 INFO app.py 30 logging.info.
2020-02-25 14:50:34,306 WARNING app.py 31 logging.warning.
2020-02-25 14:50:34,306 ERROR app.py 32 logging.error.
2020-02-25 14:50:34,306 CRITICAL app.py 33 logging.critical.
2020-02-25 14:52:10,438 DEBUG app.py 29 logging.debug.
2020-02-25 14:52:10,439 INFO app.py 30 logging.info.
2020-02-25 14:52:10,439 WARNING app.py 31 logging.warning.
2020-02-25 14:52:10,439 ERROR app.py 32 logging.error.
2020-02-25 14:52:10,439 CRITICAL app.py 33 logging.critical.
2020-02-25 14:52:10,858 DEBUG app.py 29 logging.debug.
2020-02-25 14:52:10,858 INFO app.py 30 logging.info.
2020-02-25 14:52:10,858 WARNING app.py 31 logging.warning.
2020-02-25 14:52:10,858 ERROR app.py 32 logging.error.
2020-02-25 14:52:10,858 CRITICAL app.py 33 logging.critical.
2020-02-25 14:52:15,360 DEBUG app.py 29 logging.debug.
2020-02-25 14:52:15,360 INFO app.py 30 logging.info.
2020-02-25 14:52:15,360 WARNING app.py 31 logging.warning.
2020-02-25 14:52:15,360 ERROR app.py 32 logging.error.
2020-02-25 14:52:15,360 CRITICAL app.py 33 logging.critical.
2020-02-25 17:12:49,800 DEBUG app.py 29 logging.debug.
2020-02-25 17:12:49,800 INFO app.py 30 logging.info.
2020-02-25 17:12:49,800 WARNING app.py 31 logging.warning.
2020-02-25 17:12:49,800 ERROR app.py 32 logging.error.
2020-02-25 17:12:49,800 CRITICAL app.py 33 logging.critical.
2020-02-25 17:12:50,113 DEBUG app.py 29 logging.debug.
2020-02-25 17:12:50,113 INFO app.py 30 logging.info.
2020-02-25 17:12:50,113 WARNING app.py 31 logging.warning.
2020-02-25 17:12:50,113 ERROR app.py 32 logging.error.
2020-02-25 17:12:50,113 CRITICAL app.py 33 logging.critical.
2020-02-25 17:15:03,121 DEBUG app.py 29 logging.debug.
2020-02-25 17:15:03,121 INFO app.py 30 logging.info.
2020-02-25 17:15:03,121 WARNING app.py 31 logging.warning.
2020-02-25 17:15:03,121 ERROR app.py 32 logging.error.
2020-02-25 17:15:03,121 CRITICAL app.py 33 logging.critical.
2020-02-25 17:15:04,606 DEBUG app.py 29 logging.debug.
2020-02-25 17:15:04,606 INFO app.py 30 logging.info.
2020-02-25 17:15:04,606 WARNING app.py 31 logging.warning.
2020-02-25 17:15:04,606 ERROR app.py 32 logging.error.
2020-02-25 17:15:04,606 CRITICAL app.py 33 logging.critical.
2020-02-25 17:15:06,994 DEBUG app.py 29 logging.debug.
2020-02-25 17:15:06,994 INFO app.py 30 logging.info.
2020-02-25 17:15:06,994 WARNING app.py 31 logging.warning.
2020-02-25 17:15:06,994 ERROR app.py 32 logging.error.
2020-02-25 17:15:06,994 CRITICAL app.py 33 logging.critical.
2020-02-25 17:15:07,340 DEBUG app.py 29 logging.debug.
2020-02-25 17:15:07,340 INFO app.py 30 logging.info.
2020-02-25 17:15:07,340 WARNING app.py 31 logging.warning.
2020-02-25 17:15:07,340 ERROR app.py 32 logging.error.
2020-02-25 17:15:07,340 CRITICAL app.py 33 logging.critical.
2020-02-25 17:15:15,894 DEBUG app.py 29 logging.debug.
2020-02-25 17:15:15,894 INFO app.py 30 logging.info.
2020-02-25 17:15:15,894 WARNING app.py 31 logging.warning.
2020-02-25 17:15:15,894 ERROR app.py 32 logging.error.
2020-02-25 17:15:15,894 CRITICAL app.py 33 logging.critical.
2020-02-25 17:15:19,354 DEBUG app.py 29 logging.debug.
2020-02-25 17:15:19,354 INFO app.py 30 logging.info.
2020-02-25 17:15:19,354 WARNING app.py 31 logging.warning.
2020-02-25 17:15:19,354 ERROR app.py 32 logging.error.
2020-02-25 17:15:19,354 CRITICAL app.py 33 logging.critical.
2020-02-25 17:15:24,880 DEBUG app.py 29 logging.debug.
2020-02-25 17:15:24,880 INFO app.py 30 logging.info.
2020-02-25 17:15:24,880 WARNING app.py 31 logging.warning.
2020-02-25 17:15:24,880 ERROR app.py 32 logging.error.
2020-02-25 17:15:24,880 CRITICAL app.py 33 logging.critical.
2020-02-25 17:46:28,578 DEBUG app.py 29 logging.debug.
2020-02-25 17:46:28,579 INFO app.py 30 logging.info.
2020-02-25 17:46:28,579 WARNING app.py 31 logging.warning.
2020-02-25 17:46:28,579 ERROR app.py 32 logging.error.
2020-02-25 17:46:28,579 CRITICAL app.py 33 logging.critical.
2020-02-25 17:46:28,856 DEBUG app.py 29 logging.debug.
2020-02-25 17:46:28,857 INFO app.py 30 logging.info.
2020-02-25 17:46:28,857 WARNING app.py 31 logging.warning.
2020-02-25 17:46:28,857 ERROR app.py 32 logging.error.
2020-02-25 17:46:28,857 CRITICAL app.py 33 logging.critical.
2020-02-25 17:54:59,184 DEBUG app.py 29 logging.debug.
2020-02-25 17:54:59,184 INFO app.py 30 logging.info.
2020-02-25 17:54:59,184 WARNING app.py 31 logging.warning.
2020-02-25 17:54:59,184 ERROR app.py 32 logging.error.
2020-02-25 17:54:59,184 CRITICAL app.py 33 logging.critical.
2020-02-25 17:54:59,440 DEBUG app.py 29 logging.debug.
2020-02-25 17:54:59,440 INFO app.py 30 logging.info.
2020-02-25 17:54:59,440 WARNING app.py 31 logging.warning.
2020-02-25 17:54:59,440 ERROR app.py 32 logging.error.
2020-02-25 17:54:59,440 CRITICAL app.py 33 logging.critical.
2020-03-03 14:41:49,418 DEBUG app.py 29 logging.debug.
2020-03-03 14:41:49,420 INFO app.py 30 logging.info.
2020-03-03 14:41:49,420 WARNING app.py 31 logging.warning.
2020-03-03 14:41:49,420 ERROR app.py 32 logging.error.
2020-03-03 14:41:49,420 CRITICAL app.py 33 logging.critical.
2020-03-03 14:52:48,316 DEBUG app.py 29 logging.debug.
2020-03-03 14:52:48,316 INFO app.py 30 logging.info.
2020-03-03 14:52:48,316 WARNING app.py 31 logging.warning.
2020-03-03 14:52:48,316 ERROR app.py 32 logging.error.
2020-03-03 14:52:48,316 CRITICAL app.py 33 logging.critical.
2020-03-03 14:54:14,611 ERROR app.py 1891 Exception on /db [GET]
Traceback (most recent call last):
  File "/Users/kotakawaguchi/.pyenv/versions/3.6.1/envs/kaggle/lib/python3.6/site-packages/mysql/connector/network.py", line 509, in open_connection
    self.sock.connect(sockaddr)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kotakawaguchi/.pyenv/versions/3.6.1/envs/kaggle/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/kotakawaguchi/.pyenv/versions/3.6.1/envs/kaggle/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/kotakawaguchi/.pyenv/versions/3.6.1/envs/kaggle/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/kotakawaguchi/.pyenv/versions/3.6.1/envs/kaggle/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/kotakawaguchi/.pyenv/versions/3.6.1/envs/kaggle/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kotakawaguchi/.pyenv/versions/3.6.1/envs/kaggle/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kotakawaguchi/PythonProjects/linebot/linebot/app.py", line 97, in db_save
    charset="utf8"
  File "/Users/kotakawaguchi/.pyenv/versions/3.6.1/envs/kaggle/lib/python3.6/site-packages/mysql/connector/__init__.py", line 179, in connect
    return MySQLConnection(*args, **kwargs)
  File "/Users/kotakawaguchi/.pyenv/versions/3.6.1/envs/kaggle/lib/python3.6/site-packages/mysql/connector/connection.py", line 95, in __init__
    self.connect(**kwargs)
  File "/Users/kotakawaguchi/.pyenv/versions/3.6.1/envs/kaggle/lib/python3.6/site-packages/mysql/connector/abstracts.py", line 716, in connect
    self._open_connection()
  File "/Users/kotakawaguchi/.pyenv/versions/3.6.1/envs/kaggle/lib/python3.6/site-packages/mysql/connector/connection.py", line 206, in _open_connection
    self._socket.open_connection()
  File "/Users/kotakawaguchi/.pyenv/versions/3.6.1/envs/kaggle/lib/python3.6/site-packages/mysql/connector/network.py", line 512, in open_connection
    errno=2003, values=(self.get_address(), _strioerror(err)))
mysql.connector.errors.InterfaceError: 2003: Can't connect to MySQL server on 'mysql8078.xserver.jp:3306' (60 Operation timed out)
2020-03-03 15:05:24,343 ERROR app.py 1891 Exception on /db [GET]
Traceback (most recent call last):
  File "/Users/kotakawaguchi/.pyenv/versions/3.6.1/envs/kaggle/lib/python3.6/site-packages/mysql/connector/network.py", line 509, in open_connection
    self.sock.connect(sockaddr)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kotakawaguchi/.pyenv/versions/3.6.1/envs/kaggle/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/kotakawaguchi/.pyenv/versions/3.6.1/envs/kaggle/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/kotakawaguchi/.pyenv/versions/3.6.1/envs/kaggle/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/kotakawaguchi/.pyenv/versions/3.6.1/envs/kaggle/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/kotakawaguchi/.pyenv/versions/3.6.1/envs/kaggle/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kotakawaguchi/.pyenv/versions/3.6.1/envs/kaggle/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kotakawaguchi/PythonProjects/linebot/linebot/app.py", line 97, in db_save
    charset="utf8"
  File "/Users/kotakawaguchi/.pyenv/versions/3.6.1/envs/kaggle/lib/python3.6/site-packages/mysql/connector/__init__.py", line 179, in connect
    return MySQLConnection(*args, **kwargs)
  File "/Users/kotakawaguchi/.pyenv/versions/3.6.1/envs/kaggle/lib/python3.6/site-packages/mysql/connector/connection.py", line 95, in __init__
    self.connect(**kwargs)
  File "/Users/kotakawaguchi/.pyenv/versions/3.6.1/envs/kaggle/lib/python3.6/site-packages/mysql/connector/abstracts.py", line 716, in connect
    self._open_connection()
  File "/Users/kotakawaguchi/.pyenv/versions/3.6.1/envs/kaggle/lib/python3.6/site-packages/mysql/connector/connection.py", line 206, in _open_connection
    self._socket.open_connection()
  File "/Users/kotakawaguchi/.pyenv/versions/3.6.1/envs/kaggle/lib/python3.6/site-packages/mysql/connector/network.py", line 512, in open_connection
    errno=2003, values=(self.get_address(), _strioerror(err)))
mysql.connector.errors.InterfaceError: 2003: Can't connect to MySQL server on 'mysql8078.xserver.jp:3306' (60 Operation timed out)
2020-03-03 15:35:43,717 DEBUG app.py 29 logging.debug.
2020-03-03 15:35:43,718 INFO app.py 30 logging.info.
2020-03-03 15:35:43,718 WARNING app.py 31 logging.warning.
2020-03-03 15:35:43,718 ERROR app.py 32 logging.error.
2020-03-03 15:35:43,719 CRITICAL app.py 33 logging.critical.
2020-03-03 15:36:07,985 DEBUG app.py 29 logging.debug.
2020-03-03 15:36:07,985 INFO app.py 30 logging.info.
2020-03-03 15:36:07,985 WARNING app.py 31 logging.warning.
2020-03-03 15:36:07,985 ERROR app.py 32 logging.error.
2020-03-03 15:36:07,986 CRITICAL app.py 33 logging.critical.
2020-03-03 15:53:36,643 DEBUG app.py 29 logging.debug.
2020-03-03 15:53:36,644 INFO app.py 30 logging.info.
2020-03-03 15:53:36,644 WARNING app.py 31 logging.warning.
2020-03-03 15:53:36,644 ERROR app.py 32 logging.error.
2020-03-03 15:53:36,644 CRITICAL app.py 33 logging.critical.
2020-03-03 15:57:00,521 DEBUG app.py 29 logging.debug.
2020-03-03 15:57:00,521 INFO app.py 30 logging.info.
2020-03-03 15:57:00,521 WARNING app.py 31 logging.warning.
2020-03-03 15:57:00,521 ERROR app.py 32 logging.error.
2020-03-03 15:57:00,522 CRITICAL app.py 33 logging.critical.
